resources:
  repositories:
  - repository: templates
    type: git
    name: AL_scripts  

extends:
  template: extension.yml@templates
  parameters:
    versions: []  #fill base versions that extension should be compiled against to. for e.g. 'release135', 'release129'
    environments: [] #fill environments name, where extension should be deployed. for e.g. 'cltesting', 'kwtesting'
    dependantApps: []  #fill id of pipelines, that this extension denepnds on. for e.g. 253,254
